- name: add the julia repository
  apt_repository: repo='ppa:staticfloat/juliareleases' state=present
  
- name: add the julia deps repository
  apt_repository: repo='ppa:staticfloat/julia-deps' state=present

- name: install julia
  apt: update_cache=yes name='julia'

- name: create packages directory
  file: path=/opt/global-packages state=directory

- name: add package path to juliarc
  lineinfile: dest=/usr/etc/julia/juliarc.jl line='push!(LOAD_PATH, "/opt/global-packages/.julia/v0.4/")'

- name: define JULIA_PKGDIR
  lineinfile: dest=/etc/environment line='export JULIA_PKGDIR=/opt/global-packages/.julia/'

- name: create jupyter kernel directory
  file: path=/usr/local/share/jupyter/kernels state=directory

- name: init julia
  command: julia -e 'Pkg.init()'
  args:
    creates: /opt/global-packages/.julia/v0.4/
  environment:
    JULIA_PKGDIR: /opt/global-packages/.julia/

- name: install ijulia
  command: julia -e 'Pkg.add("IJulia"); Pkg.build("IJulia")'
  args:
    creates: /opt/global-packages/.julia/v0.4/IJulia
  environment:
    JULIA_PKGDIR: /opt/global-packages/.julia/

- name: install the kernel
  command: jupyter kernelspec install /root/.local/share/jupyter/kernels/julia-0.4
  args:
    creates: /usr/local/share/jupyter/kernels/julia-0.4
