- name: create jupyterhub folder in etc
  file: path=/etc/jupyterhub state=directory mode=0755 owner=jupyter group=jupyter
  tags: jupyter

- name: copy jupyterhub sudospawner sudo config
  copy: src=sudo_jupyter dest=/etc/sudoers.d/jupyter mode=0440 owner=root group=root
  tags: jupyter

- name: copy requirements file for jupyterhub
  copy: src=jupyterhub_requirements.txt dest=/root/jupyterhub_requirements.txt
  tags: jupyter

- name: install jupyterhub, sudospawner via pip3
  pip: executable=pip3 requirements="/root/jupyterhub_requirements.txt" extra_args='--upgrade'
  tags: jupyter
  environment:
    JUPYTER_CONFIG_DIR: '/etc/jupyter'
    JUPYTER_DATA_DIR: '/usr/local/share/jupyter'

- name: install sudospawner via pip3
  pip: executable=pip3 name="git+https://github.com/jupyter/sudospawner" extra_args='--upgrade' editable=false
  tags: jupyter
  environment:
    JUPYTER_CONFIG_DIR: '/etc/jupyter'
    JUPYTER_DATA_DIR: '/usr/local/share/jupyter'

- name: configure jupyterhub
  template:
    src: ../templates/jupyterhub_config.py.j2
    dest: "{{ _jhc_config }}"
    mode: 0770
    owner: jupyter
    group: jupyter

- name: install jupyterhub upstart script
  template:
    src: ../templates/jupyterhub.conf
    dest: /etc/init/jupyterhub.conf
    mode: 755
    owner: root
    group: root
  tags: jupyter

- name: symbolic link to src dir
  file:
    src: /etc/init/jupyterhub.conf
    dest: /etc/init.d/jupyterhub
    state: link
  become: true

- name: Ensure hostname is in /etc/hosts file
  lineinfile: 
    dest: /etc/hosts
    regexp: "{{ansible_hostname}}" 
    line: "{{ansible_default_ipv4.address}}  {{ansible_hostname}}"
  tags: jupyter
          
- name: install google oauth via pip3
  pip: executable=pip3 name="oauthenticator" extra_args='--upgrade' editable=false
  tags: jupyter
  environment:
    JUPYTER_CONFIG_DIR: '/etc/jupyter'
    JUPYTER_DATA_DIR: '/usr/local/share/jupyter'
